food/urls.py
from . import views
from django.urls import path

app_name = 'food'

urlpatterns = [
    #/food/
    path('',views.index,name='index'),
    #/food/1
    path('<int:item_id>/',views.details,name='detail'),
    #/food/item
    path('item/',views.item, name="item"),
    path('add/',views.create_item,name="create_item"),
    # edit path
    path('update/<int:id>/',views.update_item,name="update_item"),
    path('delete/<int:id>/',views.delete_item,name="delete_item"),
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as users_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',users_views.register,name="register"),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',users_views.profilepage,name="profile"),
]
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    def __str__(self) -> str:
        return self.item_name

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField() 
    item_image = models.CharField(max_length=500, default="https://cdn.dribbble.com/users/1515327/screenshots/4328124/cooking_loader_2_still.gif?resize=400x0")

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item


class Itemform(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name","item_desc","item_price","item_image"]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class registerForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import Itemform
# Create your views here.
def index(request):
    item_list = Item.objects.all()
    
    context = { 
        'item_list' : item_list
    }
    return render(request,"food/index.html",context)

def item(request):
    return HttpResponse("<h1>This is an Item Page.</h1>")

def details(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        "item" : item,
    }
    return render(request,"food/details.html",context)


def create_item(request):
    form = Itemform(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form})


    # if request.method == "POST":
    #     form = Itemform(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('food:index')
    # else:
    #     form = Itemform()
    # return render( request,'food/item-form.html',{"form": form})



    
def update_item(request,id):
    item = Item.objects.get(id=id)
    form = Itemform(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == "POST":
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import registerForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == "POST":
        form = registerForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"Welcome {username}, Your account is created.")
            return redirect('login')
        
    else:
        form = registerForm
    return render(request,'users/registers.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <title>Food</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>

        <div class="navbar">
        <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Items</a>
        <a href="#" class="nav-item  nav-link" >Delete Item</a>
        <a href="#" class="nav-item nav-link ">View Item</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}" class="nav-item  nav-link">Profile </a>
            <a href="{% url 'logout' %}" class="nav-item  nav-link">logout</a>
        {% else %}
        
        <a href="{% url 'login' %}">login</a>
        {% endif %}
        </div>
    </nav>
    {% if messages %}
        {%for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
         {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
    
</body>
</html>

food/templates/food/details.html
{% extends 'food/base.html' %}
{% block body %}
<div class='container'>
    <div class='row'>
         <div class = 'col-md-6'>
            <img height = '300px' src="{{ item.item_image }}" class = 'card'>
         </div>
         <div class = 'col-md-6'>
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>${{item.item_price}}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
         </div>
    </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food HOME</title>

</head>
<body>
    {% block body %}
    
<!-- {%for item in item_list%}
    
    <ul>
        <li>
            {{item.id }}-<a href="{% url 'food:detail' item.id %}"><button>{{item.item_name}}</button></a>  
        </li>
    </ul>
    {%endfor%} -->
    {%for item in item_list%}
    <div class = "row">
        <div class="col-md-3 offset-md-2">
            <img class = 'card' height = '150px' src = "{{ item.item_image }}">
        </div>
        <div class="col-md-4">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>${{item.item_price}}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>    
        </div>
    </div>
    {%endfor%}

    {% endblock %}
    
</body>
</html>

food/templates/food/item-delete.html
<form method = "POST" >
    {% csrf_token %}
    <h2>ARE YOU SURE YOU WANT TO DELETE {{item.item_name}}</h2>
    <button type = "submit">Conform</button>
</form>

food/templates/food/item-form.html
{% extends "food/base.html" %}
{% block body %}
<form method = "post">
    {% csrf_token %}
    {{ form }}
    <button type = "submit">Save</button> 
</form>
{% endblock body %}

users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type = "submit">Login</button>
</form>

users/templates/users/logout.html
<h1>You have been logout</h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" >

users/templates/users/registers.html
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Singup</button>
</form>